# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/matriz_celda/matriz_celda.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda || ORIG_REF_NAME==matriz_celda} -quiet] -quiet

# IP: bd/matriz_celda/ip/matriz_celda_processing_system7_0_0/matriz_celda_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda_processing_system7_0_0 || ORIG_REF_NAME==matriz_celda_processing_system7_0_0} -quiet] -quiet

# IP: bd/matriz_celda/ip/matriz_celda_matriz_celda_0_0/matriz_celda_matriz_celda_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda_matriz_celda_0_0 || ORIG_REF_NAME==matriz_celda_matriz_celda_0_0} -quiet] -quiet

# IP: bd/matriz_celda/ip/matriz_celda_ps7_0_axi_periph_0/matriz_celda_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda_ps7_0_axi_periph_0 || ORIG_REF_NAME==matriz_celda_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/matriz_celda/ip/matriz_celda_rst_ps7_0_100M_0/matriz_celda_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda_rst_ps7_0_100M_0 || ORIG_REF_NAME==matriz_celda_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/matriz_celda/ip/matriz_celda_auto_pc_0/matriz_celda_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==matriz_celda_auto_pc_0 || ORIG_REF_NAME==matriz_celda_auto_pc_0} -quiet] -quiet

# XDC: bd/matriz_celda/matriz_celda_ooc.xdc
