# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Dariel/Otros/Programacion/Xilinx/Vivado/reversi/reversi.srcs/sources_1/bd/matriz_celda/ip/matriz_celda_auto_pc_0/matriz_celda_auto_pc_0.xci
# IP: The module: 'matriz_celda_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dariel/Otros/Programacion/Xilinx/Vivado/reversi/reversi.srcs/sources_1/bd/matriz_celda/ip/matriz_celda_auto_pc_0/matriz_celda_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matriz_celda_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Dariel/Otros/Programacion/Xilinx/Vivado/reversi/reversi.srcs/sources_1/bd/matriz_celda/ip/matriz_celda_auto_pc_0/matriz_celda_auto_pc_0.xci
# IP: The module: 'matriz_celda_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dariel/Otros/Programacion/Xilinx/Vivado/reversi/reversi.srcs/sources_1/bd/matriz_celda/ip/matriz_celda_auto_pc_0/matriz_celda_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matriz_celda_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
